baseURL = "https://abcedarian.blog/"
languageCode = "zh-cn"
title = "Sayu 的博客"
theme = "minimal-black"

[pagination]
  pagerSize = 6

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 3
